security:
  user:
    password: password
logging:
  level:
    org.springframework.security: DEBUG


multipart:
  maxFileSize: 512KB
  maxRequestSize: 512KB
spring:
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**